### ISSUE TITLE
can not show for checkboxes for saved nodes as checked in tree

### ISSUE THREAD

**Issue by sertac** [xrmx/django-fancytree#7]
django-fancytree saves checked nodes into db
but when it reads back from db it can not show checked nodes in tree

**Comment by xrmx** [comment]
Thanks for reporting. Will take a look, any chance you can post a reproducer?

**Comment by sertac** [comment]
You can try this in demo categories app that you provided in project
5 Nis 2015 22:29 tarihinde "Riccardo Magliocchetti" <
notifications@github.com> yazdı:

**Comment by xrmx** [comment]
If you look at the views.py source code, you'll see the form isn't saved, so nothing strange here :)

**Comment by sertac** [comment]
found my problem, now selected nodes ok on tree if we change select to selected

def get_doc(node, values):
    if hasattr(node, "get_doc"):
        return node.get_doc(values)
    if hasattr(node, "name"):
        name = node.name
    else:
        name = unicode(node)
    doc = {"title": name, "key": node.pk}
    if str(node.pk) in values:
        doc['selected'] = True ######changed line select to selected#########
        doc['expand'] = True
    return doc

def recursive_node_to_dict(node, values):
    result = get_doc(node, values)
    children = [recursive_node_to_dict(c, values) for c in node.get_children()]
    if children:
        expand = [c for c in children if c.get('selected', False)] ####changed line select to selected#####
        if expand:
            result["expand"] = True
        result["folder"] = True
        result['children'] = children
    return result

**Comment by xrmx** [comment]
@sertac I've released 0.3.0 with your fix please give it a try. Thanks!

**Comment by sertac** [comment]
perfect thanks
