### ISSUE TITLE
only root nodes selected with select-mode 3

### ISSUE THREAD

**Issue by sertac** [xrmx/django-fancytree#8]
django-fancytree is missing checking child nodes when parent node is selected with select-mode = 3

**Comment by xrmx** [comment]
Thanks for reporting. Could you please give me an example of a tree listing which nodes you are selecting and what the output is?

**Comment by sertac** [comment]
$(".fancytree_checkboxes").hide();
widgets.py line 96
please change this line to 
$(".fancytree_checkboxes").show();

and any tree is fine just create parent node then child nodes for parent node 
click to check checkbox of child node and you will see that only parent node will be checked at "fancytree_checkboxes"

**Comment by xrmx** [comment]
To me it looks like mode 3 is completely broken. We're possibly missing some node attributes in the source so the js is confused. I'd say to just avoid it for now.
